author: Xzonn
defaults:
  - values:
      layout: "default"
exclude:
  - BW_2/
  - Codes/
  - Files/
  - Debug/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - "*.less"
  - "*.psd"
image_cdn: https://images.xzonn.top/pg4
kramdown:
  syntax_highlighter_opts:
    css_class: "highlight"
locale: zh_CN
markdown: kramdown
name: 《宝可梦》第四世代汉化修正
plugins:
  - jekyll-sitemap
  - jekyll-sass-converter
timezone: Asia/Shanghai
title: 《宝可梦》第四世代汉化修正
url: https://pg4.xzonn.top