name: Build

on:
  workflow_call:
concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 2
      - uses: actions/checkout@v4
        with:
          repository: Xzonn/PCTRTools
          ref: master
          fetch-depth: 1
          path: tools
          submodules: recursive
      - name: Get tools commit id
        id: get-tools-commit-id
        run: |
          Push-Location tools/
          Write-Output "id=$(git rev-parse HEAD)" >> $env:GITHUB_OUTPUT
          Pop-Location
      - name: Cache tools
        id: cache-tools
        uses: actions/cache@v3
        with:
          path: tools/PCTRTools/bin/Release/
          key: tools-${{ steps.get-tools-commit-id.outputs.id }}
      - uses: microsoft/setup-msbuild@v1
        if: ${{ steps.cache-tools.outputs.cache-hit != 'true' }}
      - name: Build tools
        if: ${{ steps.cache-tools.outputs.cache-hit != 'true' }}
        run: |
          Push-Location tools/
          nuget restore
          msbuild /p:Configuration=Release /p:TargetFramework=net48 /verbosity:minimal
          Pop-Location
      - name: Commit Information
        id: commit
        run: |
          echo "commit_message=$(git log -1 --pretty=%s)" >> $env:GITHUB_OUTPUT
          echo "changed_dp=$(git diff --name-only HEAD..HEAD~1 | Select-String -Pattern '(files|textures)[\\/]((DP|D|P)[\\/]|CharTable.txt)')" >> $env:GITHUB_OUTPUT
          echo "changed_pt=$(git diff --name-only HEAD..HEAD~1 | Select-String -Pattern '(files|textures)[\\/]((Pt|DP)[\\/]|CharTable.txt)')" >> $env:GITHUB_OUTPUT
          echo "changed_hgss=$(git diff --name-only HEAD..HEAD~1 | Select-String -Pattern '(files|textures)[\\/]((HGSS|HG|SS|DP)[\\/]|CharTable.txt)')" >> $env:GITHUB_OUTPUT
      - name: Configure dotnet script
        run: |
          Try
          {
            if (dotnet-script -h) {}
          }
          Catch
          {
            dotnet tool install -g dotnet-script
          }
      - name: Diamond and Pearl
        if: steps.commit.outputs.changed_dp != ''
        continue-on-error: true
        run: |
          scripts/DP.ps1
      - name: Platinum
        if: steps.commit.outputs.changed_pt != ''
        continue-on-error: true
        run: |
          scripts/Pt.ps1
      - name: Heart Gold and Soul Silver
        if: steps.commit.outputs.changed_hgss != ''
        continue-on-error: true
        run: |
          scripts/HGSS.ps1
      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "out/Patch-*.zip"
          body: |
            [![Create txt](https://github.com/Xzonn/PCTRAutoBuild/actions/workflows/convert.yml/badge.svg)](https://github.com/Xzonn/PCTRAutoBuild/actions/workflows/convert.yml)

            本页面下方的链接为自动构建并发布的开发版本补丁。此版本补丁可能存在较多问题，仅供测试使用。

            请访问 [此处](https://github.com/Xzonn/NitroPatcher/releases/latest/) 获取补丁应用工具。
          name: "${{ steps.commit.outputs.commit_message }}"
          tag: publish
          token: ${{ secrets.GITHUB_TOKEN }}