name: Build

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare for Build
      run: |
        git clone --depth=1 --branch=dist --single-branch "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" dist
    - name: Pt
      continue-on-error: true
      run: |
        rm dist/Pt/Revised/Messages.txt -force
        bin/PokemonCTRFont -c src/CharTable.txt -f src/Pt_Font.narc -o dist/Pt/Revised/data/graphic/pl_font.narc
        bin/PokemonCTRText -c src/CharTable.txt -m src/Pt_Message.narc -i src/Pt.txt -o dist/Pt/Revised/data/msgdata/pl_msg.narc
        compress-archive dist/Pt/Revised/* dist/Pt/Patch-Pt.zip -force
        copy src/Pt.txt dist/Pt/Revised/Messages.txt -force
    - name: HG
      continue-on-error: true
      run: |
        rm dist/HG/Revised/Messages.txt -force
        bin/PokemonCTRFont -c src/CharTable.txt -f src/HGSS_Font.narc -o dist/HG/Revised/data/a/0/1/6
        bin/PokemonCTRText -c src/CharTable.txt -m src/HGSS_Message.narc -i src/HGSS.txt -o dist/HG/Revised/data/a/0/2/7
        compress-archive dist/HG/Revised/* dist/HG/Patch-HG.zip -force
        copy src/HGSS.txt dist/HG/Revised/Messages.txt -force
    - name: SS
      continue-on-error: true
      run: |
        rm dist/SS/Revised/Messages.txt -force
        bin/PokemonCTRFont -c src/CharTable.txt -f src/HGSS_Font.narc -o dist/SS/Revised/data/a/0/1/6
        bin/PokemonCTRText -c src/CharTable.txt -m src/HGSS_Message.narc -i src/HGSS.txt -o dist/SS/Revised/data/a/0/2/7
        compress-archive dist/SS/Revised/* dist/SS/Patch-SS.zip -force
        copy src/HGSS.txt dist/SS/Revised/Messages.txt -force
    - name: Deploy to GitHub
      run: |
        cd dist/
        git add -A
        git -c user.name=GitHub -c user.email=noreply@github.com commit -m "From GitHub Actions build ${{ github.run_number }}"
        git push
        cd ../
    - name: GitHub Release
      uses: svenstaro/upload-release-action@v2
      with:
        file: |
          dist/Pt/Patch-Pt.zip
          dist/HG/Patch-HG.zip
          dist/SS/Patch-SS.zip
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}