name: Build

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare for Build
      run: |
        git clone --depth=1 --branch=dist --single-branch "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" dist
    - name: Pt
      continue-on-error: true
      run: |
        rm dist/Pt/Revised/Messages.txt -force
        bin/PokemonCTRFont -c src/CharTable.txt -f src/Pt_Font.narc -o dist/Pt/Revised/data/graphic/pl_font.narc
        bin/PokemonCTRText -c src/CharTable.txt -m src/Pt_Message.narc -i src/Pt.txt -o dist/Pt/Revised/data/msgdata/pl_msg.narc
        compress-archive dist/Pt/Revised/* dist/Pt/Patch-Pt.zip -force
        copy src/Pt.txt dist/Pt/Revised/Messages.txt -force
    - name: HGSS
      continue-on-error: true
      run: |
        rm dist/HGSS/Revised/Messages.txt -force
        bin/PokemonCTRFont -c src/CharTable.txt -f src/HGSS_Font.narc -o dist/HGSS/Revised/data/a/0/1/6
        bin/PokemonCTRText -c src/CharTable.txt -m src/HGSS_Message.narc -i src/HGSS.txt -o dist/HGSS/Revised/data/a/0/2/7
        compress-archive dist/HGSS/Revised/* dist/HGSS/Patch-HGSS.zip -force
        copy src/HGSS.txt dist/HGSS/Revised/Messages.txt -force
    - name: Deploy to GitHub
      run: |
        cd dist/
        git add -A
        git -c user.name=GitHub -c user.email=noreply@github.com commit -m "From GitHub Actions build ${{ github.run_number }}"
        git push
        cd ../