name: Build

on:
  push:
    branches: 
      - master
      - test
  pull_request:
    branches: 
      - master
      - test

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Commit Information
      id: commit
      run: |
        echo "::set-output name=commit_id::commit-$(git rev-parse --short HEAD)"
        echo "::set-output name=commit_message::$(git log -1 --pretty=%B)"
    - name: Prepare for Build
      run: |
        git clone --depth=1 --branch=dist --single-branch "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" dist
    - name: Character Table
      run: |
        copy src/CharTable.txt dist/CharTable/Expanded.txt -force
    - name: Pt
      continue-on-error: true
      run: |
        rm dist/Pt/Revised/Messages.txt -force
        bin/PokemonCTRFont -c src/CharTable.txt -f src/Pt_Font.narc -o dist/Pt/Revised/data/graphic/pl_font.narc
        bin/PokemonCTRText -c src/CharTable.txt -m src/Pt_Message.narc -i src/Pt.txt -o dist/Pt/Revised/data/msgdata/pl_msg.narc
        compress-archive dist/Pt/Revised/* dist/Pt/Patch-Pt.zip -force
        copy src/Pt.txt dist/Pt/Revised/Messages.txt -force
    - name: HG
      continue-on-error: true
      run: |
        rm dist/HG/Revised/Messages.txt -force
        bin/PokemonCTRFont -c src/CharTable.txt -f src/HGSS_Font.narc -o dist/HG/Revised/data/a/0/1/6
        bin/PokemonCTRText -c src/CharTable.txt -m src/HGSS_Message.narc -i src/HGSS.txt -o dist/HG/Revised/data/a/0/2/7
        compress-archive dist/HG/Revised/* dist/HG/Patch-HG.zip -force
        copy src/HGSS.txt dist/HG/Revised/Messages.txt -force
    - name: SS
      continue-on-error: true
      run: |
        rm dist/SS/Revised/Messages.txt -force
        copy dist/HG/Revised/data/a/0/1/6 dist/SS/Revised/data/a/0/1/6
        copy dist/HG/Revised/data/a/0/2/7 dist/SS/Revised/data/a/0/2/7
        compress-archive dist/SS/Revised/* dist/SS/Patch-SS.zip -force
        copy src/HGSS.txt dist/SS/Revised/Messages.txt -force
    - name: Deploy to GitHub
      run: |
        cd dist/
        git add -A
        git -c user.name=GitHub -c user.email=noreply@github.com commit -m "${{ steps.commit.outputs.commit_message }}" -m "Based on commit ${{ steps.commit.outputs.commit_id }}, from GitHub Actions build ${{ github.run_number }}"
        git push
        cd ../
    - name: GitHub Release
      uses: ncipollo/release-action@v1
      continue-on-error: true
      with:
        allowUpdates: true
        artifacts: "dist/Pt/Patch-Pt.zip,dist/HG/Patch-HG.zip,dist/SS/Patch-SS.zip"
        bodyFile: Readme.md
        commit: dist
        name: ${{ steps.commit.outputs.commit_message }}
        tag: action-${{ github.run_number }}
        token: ${{ secrets.GITHUB_TOKEN }}