name: Build

on:
  workflow_call:

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 2
      - uses: actions/checkout@v4
        with:
          repository: Xzonn/PCTRTools
          ref: master
          fetch-depth: 1
          path: tools
          submodules: recursive
      - name: Get tools commit id
        id: get-tools-commit-id
        run: |
          Push-Location tools/
          Write-Output "id=$(git rev-parse HEAD)" >> $env:GITHUB_OUTPUT
          Pop-Location
      - name: Cache tools
        id: cache-tools
        uses: actions/cache@v3
        with:
          path: tools/PCTRTools/bin/Release/
          key: tools-${{ steps.get-tools-commit-id.outputs.id }}
      - uses: microsoft/setup-msbuild@v1
        if: ${{ steps.cache-tools.outputs.cache-hit != 'true' }}
      - name: Build tools
        if: ${{ steps.cache-tools.outputs.cache-hit != 'true' }}
        run: |
          Push-Location tools/
          nuget restore
          msbuild /p:Configuration=Release /p:TargetFramework=net48 /verbosity:minimal
          Pop-Location
      - name: Commit Information
        id: commit
        run: |
          echo "commit_message=$(git log -1 --pretty=%s)" >> $env:GITHUB_OUTPUT
          echo "changed_dp=$(git diff --name-only HEAD..HEAD~1 | Select-String -Pattern '\.github[\\/]workflows[\\/]|files[\\/](?:(?:DP|D|P)[\\/]|CharTable\.txt)|textures[\\/](?:DP|D|P)[\\/]|scripts[\\/](?:DP|D|P)\.')" >> $env:GITHUB_OUTPUT
          echo "changed_pt=$(git diff --name-only HEAD..HEAD~1 | Select-String -Pattern '\.github[\\/]workflows[\\/]|files[\\/](?:Pt[\\/]|CharTable\.txt)|textures[\\/](?:DP|Pt)[\\/]|scripts[\\/]Pt\.')" >> $env:GITHUB_OUTPUT
          echo "changed_hgss=$(git diff --name-only HEAD..HEAD~1 | Select-String -Pattern '\.github[\\/]workflows[\\/]|files[\\/](?:(?:HGSS|HG|SS)[\\/]|CharTable\.txt)|textures[\\/](?:DP|HGSS)[\\/]|scripts[\\/](?:HGSS|HG|SS)\.')" >> $env:GITHUB_OUTPUT
      - name: Configure dotnet script
        run: |
          Try
          {
            if (dotnet-script -h) {}
          }
          Catch
          {
            dotnet tool install -g dotnet-script
          }
      - name: Diamond and Pearl
        if: steps.commit.outputs.changed_dp != ''
        continue-on-error: true
        run: |
          scripts/DP.ps1
        env:
          XZ_PATCH_VERSION: "${{ github.sha }}"
      - name: Platinum
        if: steps.commit.outputs.changed_pt != ''
        continue-on-error: true
        run: |
          scripts/Pt.ps1
        env:
          XZ_PATCH_VERSION: "${{ github.sha }}"
      - name: Heart Gold and Soul Silver
        if: steps.commit.outputs.changed_hgss != ''
        continue-on-error: true
        run: |
          scripts/HGSS.ps1
        env:
          XZ_PATCH_VERSION: "${{ github.sha }}"
      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "out/Patch-*.zip"
          body: |
            本页面下方的链接为自动构建并发布的开发版本补丁。**此版本补丁可能存在较多问题，仅供测试使用。**

            开发版本补丁的原始 ROM 均为日本版，md5 校验码如下：

            - [《钻石》](https://datomatic.no-intro.org/index.php?page=show_record&s=28&n=6641)：`c1d66b8d4fbdbfa57ff4868970fe19d2`
            - [《珍珠》](https://datomatic.no-intro.org/index.php?page=show_record&s=28&n=4929)：`751d4a0524e4ef38b153ccfb5d21271f`
            - [《白金》](https://datomatic.no-intro.org/index.php?page=show_record&s=28&n=2641)：`8271f64f5c7fb299adf937a8be6d8c88`
            - [《心金》](https://datomatic.no-intro.org/index.php?page=show_record&s=28&n=4168)：`e3f7933aee8cc2694629293f16c1c0a8`
            - [《魂银》](https://datomatic.no-intro.org/index.php?page=show_record&s=28&n=4169)：`a1211b2d44e551197712177e3d50b491`

            请访问 [此处](https://github.com/Xzonn/NitroPatcher/releases/latest/) 获取补丁应用工具。
          name: "${{ steps.commit.outputs.commit_message }}"
          prerelease: true
          tag: dev-pub
          token: ${{ secrets.GITHUB_TOKEN }}